### ISSUE TITLE
Broken/missing emotes

### ISSUE THREAD

**Issue by ghost** [nikitahaley/teledildonics#37] opened 2017-04-24 01:41 UTC
Place emotes that are missing, broken, or don't call that worked/were present in previous versions.

:toxic: is missing, should call https://surgeshitsquad.com/mediawiki/index.php/File:Britneytoxic.jpg

**Comment by nikitahaley** [comment] 2017-11-22 09:26
duplicate of #49

**Closed as completed by nikitahaley** 2017-11-22 09:26 UTC
Labels: bug, duplicate
